import { connect, out, shot, sleep } from './cdp.mjs';
const B = 'http://localhost:3000', S = 'pharmacie-pilote';
const j = async (p, o = {}, t) => { const r = await fetch(B + p, { method: o.method, headers: { 'content-type': 'application/json', ...(t ? { authorization: 'Bearer ' + t } : {}) }, body: o.body && JSON.stringify(o.body) }); return { s: r.status, b: await r.json().catch(() => null) }; };
const t = (await j('/auth/login', { method: 'POST', body: { email: 'admin@example.com', password: 'ChangeMe123!', tenantSlug: S } })).b.accessToken;
const ph = '06' + String(Math.floor(1e7 + Math.random() * 9e7)).padStart(7, '0');
const cr = (await j('/online-orders/couriers', { method: 'POST', body: { name: 'Patrick M.', phone: ph, pin: '1357' } }, t)).b;
const cph = '05' + String(Math.floor(1e6 + Math.random() * 9e6));
const rg = (await j(`/online/${S}/register`, { method: 'POST', body: { name: 'Mme Ndinga', phone: cph + '00', password: 'secret12' } })).b;
const cat = (await j(`/online/${S}/catalog?take=60`)).b.items;
const pick = (n) => cat.find((i) => i.name.startsWith(n) && i.available);
const items = [pick('Doliprane'), pick('Vitamine C'), pick('Sels')].filter(Boolean).map((i) => ({ productId: i.id, quantity: 1 }));
const od = (await j(`/online/${S}/orders`, { method: 'POST', body: { items, fulfilment: 'delivery', address: 'Avenue de la Paix, Poto-Poto, Brazzaville', addressNote: 'Face à la boulangerie', paymentMethod: 'mtn_momo', paymentRef: 'MP' + Date.now() } }, rg.token)).b;
await j(`/online-orders/${od.id}/accept`, { method: 'POST' }, t);
await j(`/online-orders/${od.id}/assign`, { method: 'POST', body: { courierId: cr.id } }, t);
await j(`/online-orders/${od.id}/confirm-payment`, { method: 'POST' }, t);
await j(`/online-orders/${od.id}/status`, { method: 'POST', body: { status: 'ready' } }, t);
const cl = (await j(`/online/${S}/courier/login`, { method: 'POST', body: { phone: ph, pin: '1357' } })).b;
const c = await connect();
await c.send('Page.enable');
await c.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: true });
await c.send('Page.navigate', { url: `http://localhost:5173/livreur/${S}` });
await sleep(1200);
await c.evalJs(`localStorage.setItem('courier.${S}.token', ${JSON.stringify(JSON.stringify(cl.token))}); localStorage.setItem('courier.${S}.name', ${JSON.stringify(JSON.stringify(cl.name))}); true`);
await c.send('Page.reload');
await sleep(4500);
await shot(c, out('m-courier2.png'));
// client : panier rempli + commandes
await c.send('Page.navigate', { url: `http://localhost:5173/boutique/${S}` });
await sleep(1200);
await c.evalJs(`localStorage.setItem('shop.${S}.token', ${JSON.stringify(JSON.stringify(rg.token))}); true`);
await c.send('Page.reload');
await sleep(3500);
await c.evalJs(`[...document.querySelectorAll('nav button')].find(b=>b.textContent.includes('commandes')).click(); true`);
await sleep(2500);
await shot(c, out('m-orders.png'));
console.log('ok');
c.close();
